In [114]:
import numpy as np
import pandas as pd
from datetime import datetime
from pathlib import Path
import peakutils
from peakutils.plot import plot as pplot
from matplotlib import pyplot

import talib

In [186]:
class CSVDataHandler:
    def __init__(self, csv_dir, symbol_list, timeframe):
        self.csv_dir = csv_dir
        self.symbol_list = symbol_list
        self.timeframe = timeframe
        
        self.symbol_data = dict()
        self.latest_symbol_data = dict()
        
        self.continue_backtest = True
        
        self._import_symbol_data()
        
    def _import_symbol_data(self):
        csv_files_path = f'{Path().absolute()}/{self.csv_dir}'
        columns = ['datetime', 'open', 'high', 'low', 'close', 'volume']
        combined_symbol_index = None
        
        for symbol in symbol_list:
            symbol_csv_path = f'{csv_files_path}/{symbol}_{self.timeframe}.csv'
            self.symbol_data[symbol] = pd.read_csv(symbol_csv_path, header=None, index_col=0, names=columns)
            
            self.symbol_data[symbol].index = pd.to_datetime(self.symbol_data[symbol].index, unit='ms')
            self.symbol_data[symbol] = self.symbol_data[symbol].drop_duplicates()
            self.symbol_data[symbol] = self.symbol_data[symbol].sort_index()
            
            if combined_symbol_index is None:
                combined_symbol_index = self.symbol_data[symbol].index
            else:
                combined_symbol_index = combined_symbol_index.union(self.symbol_data[symbol].index)
            
            self.latest_symbol_data[symbol] = list()
            
        for symbol in symbol_list:
            self.symbol_data[symbol] = self.symbol_data[symbol].reindex(index=combined_symbol_index, method='pad', fill_value=0).itertuples()
            
    def _get_new_bar(self, symbol):
        for bar in self.symbol_data[symbol]:
            yield bar
            
    def update_bars(self):
        for symbol in self.symbol_list:
            try:
                bar = next(self._get_new_bar(symbol))
            except StopIteration:
                self.continue_backtest = False
            else:
                if bar is not None:
                    self.latest_symbol_data[symbol].append(bar)
                    
    def get_latest_bar(self, symbol):
        try:
            return self.latest_symbol_data[symbol][-1]
        except KeyError:
            print("That symbol is not available in the historical data set.")
            raise
            
    def get_latest_bars(self, symbol, N=1):
        try:
            return np.array(self.latest_symbol_data[symbol][-N:])
        except KeyError:
            print("That symbol is not available in the historical data set.")
            raise
            
    def get_latest_bar_datetime(self, symbol):
        try:
            return self.latest_symbol_data[symbol][-1].Index
        except KeyError:
            print("That symbol is not available in the historical data set.")
            raise
            
    def get_latest_bar_value(self, symbol, value_type):
        try:
            return getattr(self.latest_symbol_data[symbol][-1], value_type)
        except KeyError:
            print("That symbol is not available in the historical data set.")
            raise
            
    def get_latest_bars_values(self, symbol, value_type, N=1):
        try:
            bars = self.latest_symbol_data[symbol][-N:]
        except KeyError:
            print("That symbol is not available in the historical data set.")
            raise
        else:
            return np.array([getattr(bar, value_type) for bar in bars])

In [218]:
symbol_list = ['BTC-USDT']
data_handler = CSVDataHandler('../exchange_data', symbol_list, timeframe='1m')

/Users/redamakhoukh/.local/share/virtualenvs/promesse_trading_engine_v2-NEvk7s3j/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (0,1,2,3,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


IndexError: list index out of range

In [214]:
data_points = 3360
for i in range(3363):
    data_handler.update_bars() 

In [215]:
datetimes = data_handler.get_latest_bars_values('BTC-USDT', 'Index', N=data_points)
closes = data_handler.get_latest_bars_values('BTC-USDT', 'close', N=data_points)
data = pd.DataFrame(data=closes, index=datetimes, columns=['close'])

In [216]:
close_weekly = data.resample('W').agg({
'close': lambda x: x[-1]
})['close'].to_numpy()
close_weekly

array([ 4086.29,  4310.01,  4509.08,  4130.37,  3699.99,  3660.02,
        4378.48,  4640.  ,  5709.99,  5950.02,  6169.98,  7345.01,
        5811.03,  8038.  ,  9128.02, 11165.41, 14899.98, 18860.02,
       13500.  , 13716.36, 14513.06])

In [217]:
ma = talib.MA(close_weekly, timeperiod=20)
ma

array([      nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan, 7685.403 , 8206.7415])

In [63]:
ma

array([      nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,
             nan, 6232.583 , 6574.1755])

In [97]:
close_weekly

array([ 3667.58,  3743.56,  3807.75,  3916.82,  3981.14,  3992.18,
        4103.95,  5170.27,  5131.3 ,  5256.14,  5307.52,  5775.62,
        6967.31,  8148.48,  8614.43,  8725.98,  7628.13,  8953.33,
       10906.07, 10854.1 , 10499.43])

In [155]:
closes

array([ 4315.32,  4324.35,  4349.99, ..., 14429.  , 14539.97, 14398.97])